genomes: /Users/matija/uhgg_gff
intermediate_dir: /tmp/intermediate_dir
format1: .gff
format2: .fna
database_folder: ../resources/database/
gunc_db_type: gtdb #progenomes or gtdb
busco_parameters: --auto-lineage-prok # or specific lineage with -l flag
batch_size: 50
