genomes: ../../../genome/Rikenellaceae
input_text_file: ../../../phylum_structure/rikenellaceae.txt
temporary_dir: /scratch
directory_faa: faa_files #directory where faa files should be stored for after analysis
format1: .fasta.gz
format2: .fna.gz
database_folder: ../../resources/database/
gunc_db_type: gtdb #progenomes or gtdb
busco_parameters: cluster_analysis # specific lineage with -l flag or "cluster_analysis" or --auto-lineage-prok
batch_size: 50
all_genomes: ../../All_genomes.tsv #table where cluster is specified for every genome in genomes/ dir
busco_output: ../../BUSCO_hq_reps_output.tsv #output for BUSCO representative run
cluster_info: cluster95 #Which cluster was used to create previous busco output
